name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Emacs
        run: |
          sudo add-apt-repository ppa:kelleyk/emacs
          sudo apt update --yes && sudo apt install emacs28-nox --yes
          sudo apt install graphviz --yes
          sudo apt-get install fonts-wqy-zenhei
          export GRAPHVIZ_DOT=/usr/bin/
          sudo cp ./assets/ditaa.jar /tmp/ditaa.jar
          sudo cp ./assets/plantuml.jar /tmp/plantuml.jar
          sudo chmod 777 /tmp/ditaa.jar
          sudo chmod 777 /tmp/plantuml.jar

      - name: Build the site
        run: |
          ./build.sh
          cd _site
          git add .
          git commit -m 'update website' -a
          git push -f origin gh-pages

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./_site

      # - name: Publish generated content to GitHub Pages
      #   uses: JamesIves/github-pages-deploy-action@4.1.4
      #   with:
      #     branch: gh-pages
      #     folder: _site
